image: maven:latest

stages:
  - build
  - package
  - dockerise

Build project:
  stage: build
  script:
    - mvn compile

Package project:
  image: bellsoft/liberica-openjdk-alpine:14
  stage: package
  script:
    - chmod +x mvnw
    - ./mvnw package
  artifacts:
    paths:
      - target/test202001-0.0.1-SNAPSHOT.jar
    expire_in: 1 week

Dockerise project:
  stage: dockerise
  image: docker:latest
  services:
    - docker:dind
  script:
    - "cp target/test202001-0.0.1-SNAPSHOT.jar docker/gitlabci.jar"
    - cd docker
    - docker build -t $CI_REGISTRY_IMAGE:rcs_docker_image .
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:rcs_docker_image